on:
  workflow_call:
    inputs:
      cache:
        description: 'Enable caching of Hugo resources'
        default: true
        required: false
        type: boolean

      hugo-version:
        description: 'Specify Hugo generator version'
        default: '0.131.0'
        required: false
        type: string

      enforce-https:
        description: 'Rewrite URL to HTTPS'
        default: false
        required: false
        type: boolean

  workflow_dispatch:

env:
  VERSION: '5.0'

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy
    permissions:
      id-token: write
      pages: write

    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

        timeout-minutes: 5

      - name: Setup cache
        if: ${{ inputs.cache }} == 'true'
        uses: actions/cache@v4
        with:
          path: |
            ${{ runner.temp }}/hugo.deb
            ${{ runner.temp }}/hugo_cache
            ./resources

          key: ${{ github.workflow }}-${{ github.ref }}-${{ env.VERSION }}-${{ inputs.hugo-version }}-${{ github.run_id }}
          restore-keys: |
            ${{ github.workflow }}-${{ github.ref }}-${{ env.VERSION }}-${{ inputs.hugo-version }}-

        timeout-minutes: 5

      - name: Install Hugo CLI
        run: >
          [[ -f ${{ runner.temp }}/hugo.deb ]]
          || wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${{ inputs.hugo-version }}/hugo_extended_${{ inputs.hugo-version }}_linux-amd64.deb
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

        timeout-minutes: 5

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
        timeout-minutes: 1

      - name: Build site
        run: >
          hugo
          --baseURL "${{ inputs.enforce-https == 'true' && format('https://{0}{1}', steps.pages.outputs.host, steps.pages.outputs.base_path) || steps.pages.outputs.base_url }}/"
          --cacheDir ${{ runner.temp }}/hugo_cache
          --enableGitInfo
          --gc
          --minify

      - name: Upload artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

        timeout-minutes: 5

      - name: Deploy to Pages
        id: deployment
        if: github.ref == 'refs/heads/main'
        uses: actions/deploy-pages@v4
        timeout-minutes: 10

    timeout-minutes: 30
